all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    ec2:
      hosts:
        ec2_instance:
          ansible_host: 54.86.92.249  
          ansible_user: ubuntu       
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

