---
- name: Install Apache and Configure
  hosts: ec2_instance
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Change Apache Port to 81
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 81'

    - name: Update the VirtualHost to port 81
      lineinfile:
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: '<VirtualHost \*:80>'
        line: '<VirtualHost *:81>'

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted
        enabled: true

